src/Entity/Agenda.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AgendaRepository")
 */
class Agenda
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }
}

src/Form/AgendaType.php
<?php

namespace App\Form;

use App\Entity\Agenda;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgendaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('agendaPost', AgendaPostType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Agenda::class,
        ]);
    }
}

src/Controller/AgendaController.php
<?php

namespace App\Controller;

use App\Entity\Agenda;
use App\Form\AgendaType;
use App\Repository\AgendaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/agendad")
 */
class AgendaController extends AbstractController
{
    /**
     * @Route("/", name="agenda_index", methods={"GET"})
     */
    public function index(AgendaRepository $agendaRepository): Response
    {
        return $this->render('agenda/index.html.twig', [
            'agendas' => $agendaRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="agenda_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $agenda = new Agenda();
        $form = $this->createForm(AgendaType::class, $agenda);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($agenda);
            $entityManager->flush();

            return $this->redirectToRoute('agenda_index');
        }

        return $this->render('agenda/new.html.twig', [
            'agenda' => $agenda,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="agenda_show", methods={"GET"})
     */
    public function show(Agenda $agenda): Response
    {
        return $this->render('agenda/show.html.twig', [
            'agenda' => $agenda,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="agenda_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Agenda $agenda): Response
    {
        $form = $this->createForm(AgendaType::class, $agenda);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('agenda_index');
        }

        return $this->render('agenda/edit.html.twig', [
            'agenda' => $agenda,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="agenda_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Agenda $agenda): Response
    {
        if ($this->isCsrfTokenValid('delete'.$agenda->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($agenda);
            $entityManager->flush();
        }

        return $this->redirectToRoute('agenda_index');
    }
}

templates/agenda/_delete_form.html.twig
<form method="post" action="{{ path('agenda_delete', {'id': agenda.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agenda.id) }}">
    <button class="btn">Delete</button>
</form>

templates/agenda/_form.html.twig
{{ form_start(form) }}
    {{ form_label(form.agendaPost.intituler, "Intitulé :")}}
    {{ form_widget(form.agendaPost.intituler) }}
    {{ form_errors(form.agendaPost.intituler) }}

    {{ form_label(form.agendaPost.fait, "Fait :")}}
    {{ form_widget(form.agendaPost.fait) }}
    {{ form_errors(form.agendaPost.fait) }
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/agenda/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Agenda{% endblock %}

{% block body %}
    <h1>Edit Agenda</h1>

    {{ include('agenda/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('agenda_index') }}">back to list</a>

    {{ include('agenda/_delete_form.html.twig') }}
{% endblock %}

templates/agenda/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agenda index{% endblock %}

{% block body %}
    <h1>Agenda index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Create_at</th>
                <th>Update_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for agenda in agendas %}
            <tr>
                <td>{{ agenda.id }}</td>
                <td>{{ agenda.createAt ? agenda.createAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ agenda.updateAt ? agenda.updateAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('agenda_show', {'id': agenda.id}) }}">show</a>
                    <a href="{{ path('agenda_edit', {'id': agenda.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('agenda_new') }}">Create new</a>
{% endblock %}

templates/agenda/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Agenda{% endblock %}

{% block body %}
    <h1>Create new Agenda</h1>

    {{ include('agenda/_form.html.twig') }}

    <a href="{{ path('agenda_index') }}">back to list</a>
{% endblock %}

templates/agenda/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agenda{% endblock %}

{% block body %}
    <h1>Agenda</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agenda.id }}</td>
            </tr>
            <tr>
                <th>Create_at</th>
                <td>{{ agenda.createAt ? agenda.createAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Update_at</th>
                <td>{{ agenda.updateAt ? agenda.updateAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('agenda_index') }}">back to list</a>

    <a href="{{ path('agenda_edit', {'id': agenda.id}) }}">edit</a>

    {{ include('agenda/_delete_form.html.twig') }}
{% endblock %}